# Generated by Django 5.1.4 on 2024-12-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0020_alter_applications_applyamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='applyAmount',
            field=models.CharField(choices=[('KSH 8000.00', 'KSH 8000.00'), ('KSH 10000.00', 'KSH 10000.00')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Constituency',
            field=models.CharField(choices=[('Kibwezi West', 'Kibwezi West'), ('Kibwezi East', 'Kibwezi East'), ('Mbooni', 'Mbooni'), ('Kilome', 'Kilome')], default='Kibwezi West', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='fees_structure',
            field=models.FileField(blank=True, default='default_fees_structure.pdf', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_card',
            field=models.ImageField(blank=True, default='default_id_card.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='ward',
            field=models.CharField(choices=[('Wote', 'Wote'), ('Makindu', 'Makindu'), ('Mtito-Andei', 'Mtito-Andei'), ('Thange', 'Thange')], default='Wote', max_length=200),
        ),
    ]
