# Generated by Django 5.1.4 on 2024-12-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0021_alter_applications_applyamount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='applyAmount',
            field=models.CharField(choices=[('KSH 5000.00', 'KSH 5000.00'), ('KSH 6500.00', 'KSH 6500.00'), ('KSH 8000.00', 'KSH 8000.00'), ('KSH 10000.00', 'KSH 10000.00')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booking in Progress', 'Booking in Progress'), ('Confirmed', 'Confirmed')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bursary',
            name='category',
            field=models.CharField(choices=[('Studio', 'Studio'), ('Private Room', 'Private Room'), ('Villa', 'Villa')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Constituency',
            field=models.CharField(choices=[('Serene Stays', 'Serene Stays'), ('Haven Hills', 'Haven Hills'), ('Tranquil Pines', 'Tranquil Pines'), ('Sunset Retreat', 'Sunset Retreat')], default='Kibwezi West', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='ward',
            field=models.CharField(choices=[('Lakeside Haven', 'Lakeside Haven'), ('Whispering Pines BnB', 'Whispering Pines BnB'), ('Cozy Corner BnB', 'Cozy Corner BnB'), ('Hilltop Hideaway', 'Hilltop Hideaway')], default='None', max_length=200),
        ),
    ]
